{
 "title": "Meta information",
 "description": "Meta information about the packtrackers",
 "time": { "from": "now-48h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "myinterval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "kind", "query": "bar,line" }
  ]
 },
 "panels": [
  {
   "title": "Percentage done",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(*) filter (where status <> 'created') / count(*)::numeric as per_done FROM scrape_jobs;\n"
    }
   ]
  },
  {
   "title": "Queries over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(end_time,$myinterval,0),\n  count(id) AS \"jaja.$kind\"\nFROM scrape_jobs\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'success'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(end_time,$myinterval),\n  count(*) as \"numbers.$kind\"\nFROM\n  scrape_jobs\nWHERE\n  $__timeFilter(end_time)\n  and\n  status = 'success'\n  and\n  NOT jsonb_path_exists(resp, '$.consignmentSet[*].error')\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Request duration percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(end_time,$myinterval,NULL),\n  percentile_cont(0.25) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (end_time - start_time))*1000) as p25,\n  percentile_cont(0.50) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (end_time - start_time))*1000) as p50,\n  percentile_cont(0.75) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (end_time - start_time))*1000) as p75,\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (end_time - start_time))*1000) as p95\nFROM\n  scrape_jobs\nWHERE\n  $__timeFilter(end_time)\n  and\n  status <> 'created'\nGROUP BY time\nORDER BY time\n"
    }
   ]
  }
 ]
}